apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w5rkt933u-go-gitops
  description: This is GitOps manifest for w5rkt933u-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: w5rkt933u-go
    backstage.io/kubernetes-id: w5rkt933u-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w5rkt933u-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w5rkt933u-go
